#!/bin/bash
# XHost with docker run utility
# Author: Luiz Garcia (Axway) (c) 2020
# To do:
#

parameters=$@
command=$0

myDir="$(dirname "$command")"
source "$myDir/tools"

log()
{
  if [[ $verbose == "y" ]]
  then
    echo "$@"
  fi
}

printUsage()
{
  log "Usage:"
  log "    ./`basename $command` version"
  log
  log "Where:"
  log "    <version>  Required. Version like 7.5.3, 7.5.3.12, 7.5.3.13, 7.7.202001, 7.7.202003."
  log
  log "Examples:"
  log "    ./`basename $command` 7.5.3.13"
  log
}

parseOptions()
{
  help=”n”
  verbose=”n”

  for i in $parameters
  do
    case “$i” in
        -h|--help)
            help=y
            ;;
        -v|--verbose)
            verbose=y
            ;;
        --)
            ;;
        *)
            version=$i
            ;;
    esac
  done
}

# This is the main part of the script, the rest is more related to parse the options and supporting functions.
main()
{
  log "`basename $command` utility v1.0 2020-05-16 by Luiz Garcia - Axway"

  getImageName gateway $version
  initializeImage

  # Check if there is already the directories for that version.
  if [[ ! -d ~/Axway/gateway/$version ]]
  then
    log "Initializing directories."
    mkdir -p ~/axway/gateway/$version
    ID=$(docker container run -itd $image &) && \
      docker container cp $ID:/opt/axway/apigateway/logs/ ~/axway/gateway/$version/ && \
      docker container cp $ID:/opt/axway/apigateway/traces/ ~/axway/gateway/$version/ && \
      docker container stop $ID && \
      docker container rm $ID
  fi

  log "Running $command"
  docker container run -d -p 8090:8090 -p 8080:8080 -e COMMAND="/home/axway/hi-anm" -v ~/axway/gateway/$version/workspace:/home/axway/workspace/ -v ~/axway/gateway/$version/logs:/opt/axway/apigateway/logs/ -v ~/axway/gateway/$version/traces:/opt/axway/apigateway/traces $image /home/axway/daemon &
}

parseOptions

# handle non-option arguments
if [[ "$help" == "y" ]] || [[ $# -lt "1" ]] || [[ -z "$version" ]]
then
  verbose=y
  printUsage
else
  if [[ "$verbose" == "n" ]]
  then
    exec >/dev/null 2>&1
  fi

  # Call main function.
  main
fi
