version: '3.7'

services:
  devtools:
    image: lacg/axway_devtools_base:8
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - apiprojects:/home/axway/apiprojects
volumes:
  apiprojects:
